// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs_ARHwJRf63GRMMdrN9yI_0Y34db7Jdk',
    appId: '1:368984315537:web:1c849063b9201af48d9130',
    messagingSenderId: '368984315537',
    projectId: 'ankit-s-deep-agent',
    authDomain: 'ankit-s-deep-agent.firebaseapp.com',
    storageBucket: 'ankit-s-deep-agent.firebasestorage.app',
    measurementId: 'G-5HGQ3SYK6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiR1BET6WtV4mRyBG0tLF660tt1z8YwZ4',
    appId: '1:368984315537:android:784dcf711d7ea9e58d9130',
    messagingSenderId: '368984315537',
    projectId: 'ankit-s-deep-agent',
    storageBucket: 'ankit-s-deep-agent.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZVKU7ORlp-DjKnj7uMG42BI-di09YxyY',
    appId: '1:368984315537:ios:b61b8584f2fffd6f8d9130',
    messagingSenderId: '368984315537',
    projectId: 'ankit-s-deep-agent',
    storageBucket: 'ankit-s-deep-agent.firebasestorage.app',
    iosBundleId: 'com.ankit.ankitAgent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZVKU7ORlp-DjKnj7uMG42BI-di09YxyY',
    appId: '1:368984315537:ios:b61b8584f2fffd6f8d9130',
    messagingSenderId: '368984315537',
    projectId: 'ankit-s-deep-agent',
    storageBucket: 'ankit-s-deep-agent.firebasestorage.app',
    iosBundleId: 'com.ankit.ankitAgent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs_ARHwJRf63GRMMdrN9yI_0Y34db7Jdk',
    appId: '1:368984315537:web:3a513ed54198acbd8d9130',
    messagingSenderId: '368984315537',
    projectId: 'ankit-s-deep-agent',
    authDomain: 'ankit-s-deep-agent.firebaseapp.com',
    storageBucket: 'ankit-s-deep-agent.firebasestorage.app',
    measurementId: 'G-0JM9812EM5',
  );
}
